### ISSUE TITLE
File ownership is set to 1000:1000 instead of root:root (or other)

### ISSUE THREAD

**Issue by strushb** [yosukes-dev/RHWSL#3]
When installing the current .zip (8.4-209) and e.g. install openssh-clients and try to ssh to another host, it complains about wrong file ownership for /etc/crypto-policies/back-ends/openssh.config.

Looking into the rootfs.tar.gz, I see that all files are assigned to your local user, yosukes:yosukes. If I run your Makefile inside a WSL-Container as user id 0 the resulting tar.gz looks good (using it successfully now)

Maybe some releases are built as root and some as non-root?

**Comment by yosukes-dev** [comment]
Thank you for reporting.
I deleted the release file once to investigate the cause.

**Comment by yosukes-dev** [comment]
It may depend on the version.
In my environment, building as root user on WSL did not change the situation.
The problem was solved by building on Debian (virtual machine).
This will be reflected in the next release.
